version: "3.8"
services:
    web:
        build:
            context: ./docker
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html
        ports:
            - 81:80

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - my-datavolume:/var/lib/mysql
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/create-testing-database.sh'
        ports:
            - "3308:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8001:80
volumes:
  my-datavolume:
    driver: local
